package com.example.utils

object LocalizationManager {

    fun getString(key: String, lang: String): String {
        val map = when (lang) {
            "si" -> sinhalaStrings
            "ta" -> tamilStrings
            else -> englishStrings
        }
        return map[key] ?: englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        "settings_title" to "Settings",
        "settings_subtitle" to "Manage your FriendHub experience",
        "view_profile" to "View profile",
        "category_account" to "Account",
        "category_privacy" to "Privacy",
        "category_notifications" to "Notifications",
        "category_appearance" to "Appearance",
        "category_content" to "Content & Media",
        "category_language" to "Language",
        "category_security" to "Security",
        "category_data" to "Data & Storage",
        "category_help" to "Help & Support",
        "category_about" to "About",
        "category_session" to "Session",
        "log_out" to "Log Out",
        "log_out_confirm_title" to "Log out of FriendHub?",
        "log_out_confirm_msg" to "Are you sure you want to log out of your FriendHub account on this device?",
        "cancel" to "Cancel",
        "save" to "Save",
        "saved" to "Settings saved successfully ✓",
        "delete_account" to "Delete Account",
        "delete_account_warn" to "Deleting your account will permanently remove your profile, posts, messages, and friend connections. This action cannot be undone.",
        "account_info" to "Account Information",
        "email_phone" to "Email & Phone",
        "password_security" to "Password & Security",
        "login_activity" to "Login Activity",
        "connected_devices" to "Connected Devices",
        "profile_visibility" to "Profile Visibility",
        "friend_requests" to "Who can send friend requests",
        "who_can_message" to "Who can message me",
        "who_can_see_posts" to "Who can see my posts",
        "who_can_see_stories" to "Who can see my stories",
        "online_status" to "Online Status",
        "last_active" to "Last Active Status",
        "read_receipts" to "Read Receipts",
        "blocked_users" to "Blocked Users",
        "push_notif" to "Push Notifications",
        "msg_notif" to "Message Notifications",
        "likes_notif" to "Likes & Reactions",
        "comments_notif" to "Comments",
        "mentions_notif" to "Mentions",
        "stories_notif" to "Story Notifications",
        "email_notif" to "Email Notifications",
        "theme" to "Theme",
        "theme_dark" to "Dark",
        "theme_light" to "Light",
        "theme_system" to "System Default",
        "autoplay_videos" to "Autoplay Videos",
        "data_saver" to "Data Saver",
        "upload_quality" to "Upload Quality",
        "auto_download" to "Download Media Automatically",
        "sensitive_content" to "Sensitive Content Warning",
        "two_factor" to "Two-Step Verification",
        "login_alerts" to "Login Alerts",
        "app_lock" to "App Lock",
        "clear_cache" to "Clear Cached Media",
        "storage_usage" to "Storage Usage",
        "help_center" to "Help Center",
        "report_problem" to "Report a Problem",
        "contact_us" to "Contact FriendHub",
        "community_guidelines" to "Community Guidelines",
        "privacy_policy" to "Privacy Policy",
        "terms_of_service" to "Terms of Service",
        "app_version" to "App Version",
        "opt_everyone" to "Everyone",
        "opt_friends" to "Friends",
        "opt_only_me" to "Only Me",
        "opt_friends_of_friends" to "Friends of Friends",
        "opt_no_one" to "No One"
    )

    private val sinhalaStrings = mapOf(
        "settings_title" to "සැකසුම් (Settings)",
        "settings_subtitle" to "ඔබගේ FriendHub ගිණුම කළමනාකරණය කරන්න",
        "view_profile" to "පැතිකඩ බලන්න",
        "category_account" to "ගිණුම (Account)",
        "category_privacy" to "පෞද්ගලිකත්වය (Privacy)",
        "category_notifications" to "දැනුම්දීම් (Notifications)",
        "category_appearance" to "තේමාව (Appearance)",
        "category_content" to "අන්තර්ගතය සහ මාධ්‍ය (Content & Media)",
        "category_language" to "භාෂාව (Language)",
        "category_security" to "ආරක්ෂාව (Security)",
        "category_data" to "දත්ත සහ ගබඩාව (Data & Storage)",
        "category_help" to "උදවු සහ සහාය (Help & Support)",
        "category_about" to "FriendHub පිළිබඳව (About)",
        "category_session" to "සැසිය (Session)",
        "log_out" to "ඉවත් වන්න (Log Out)",
        "log_out_confirm_title" to "FriendHub වෙතින් ඉවත් වීමට අවශ්‍යද?",
        "log_out_confirm_msg" to "ඔබගේ මෙම දුරකථනයෙන් FriendHub ගිණුමෙන් ඉවත් වීමට ඔබට අවශ්‍ය බව සහතිකද?",
        "cancel" to "අවලංගු කරන්න",
        "save" to "සුරකින්න",
        "saved" to "සැකසුම් සාර්ථකව සුරකින ලදී ✓",
        "delete_account" to "ගිණුම මකා දමන්න (Delete Account)",
        "delete_account_warn" to "ඔබගේ ගිණුම මකා දැමීමෙන් ඔබගේ පැතිකඩ, පළකිරීම් සහ පණිවිඩ ස්ථිරවම ඉවත් වේ.",
        "account_info" to "ගිණුමේ තොරතුරු",
        "email_phone" to "ඊමේල් සහ දුරකථන අංකය",
        "password_security" to "මුරපදය සහ ආරක්ෂාව",
        "login_activity" to "පුරනය වීමේ ක්‍රියාකාරකම්",
        "connected_devices" to "සම්බන්ධිත උපාංග",
        "profile_visibility" to "පැතිකඩ දර්ශනය වීම",
        "friend_requests" to "මිතුරු ඇරයුම් එවිය හැක්කේ කාටද",
        "who_can_message" to "පණිවිඩ එවිය හැක්කේ කාටද",
        "who_can_see_posts" to "පළකිරීම් නැරඹිය හැක්කේ කාටද",
        "who_can_see_stories" to "Stories නැරඹිය හැක්කේ කාටද",
        "online_status" to "Online තත්ත්වය පෙන්වීම",
        "last_active" to "අවසන් වරට සක්‍රීය වූ වේලාව",
        "read_receipts" to "පණිවිඩ කියවූ බව පෙන්වීම (Read Receipts)",
        "blocked_users" to "අවහිර කළ ගිණුම් (Blocked Users)",
        "push_notif" to "Push දැනුම්දීම්",
        "msg_notif" to "පණිවිඩ දැනුම්දීම්",
        "likes_notif" to "Likes සහ Reactions",
        "comments_notif" to "Comments දැනුම්දීම්",
        "mentions_notif" to "Mentions දැනුම්දීම්",
        "stories_notif" to "Stories දැනුම්දීම්",
        "email_notif" to "ඊමේල් දැනුම්දීම්",
        "theme" to "තේමාව (Theme)",
        "theme_dark" to "අඳුරු (Dark)",
        "theme_light" to "දීප්තිමත් (Light)",
        "theme_system" to "දුරකථන තේමාව (System Default)",
        "autoplay_videos" to "වීඩියෝ ස්වයංක්‍රීයව වාදනය",
        "data_saver" to "දත්ත සුරැකුම (Data Saver)",
        "upload_quality" to "උඩුගත කිරීමේ ගුණාත්මකභාවය",
        "auto_download" to "මාධ්‍ය ස්වයංක්‍රීයව බාගත කිරීම",
        "sensitive_content" to "සංවේදී අන්තර්ගත අනතුරු ඇඟවීම්",
        "two_factor" to "ද්විත්ව පියවර තහවුරු කිරීම (2FA)",
        "login_alerts" to "නව පුරනය වීමේ අනතුරු ඇඟවීම්",
        "app_lock" to "යෙදුම් අගුල (App Lock)",
        "clear_cache" to "තාවකාලික මතකය ඉවත් කරන්න (Clear Cache)",
        "storage_usage" to "ගබඩා ඉඩ ප්‍රමාණය",
        "help_center" to "උදවු මධ්‍යස්ථානය",
        "report_problem" to "ගැටලුවක් වාර්තා කරන්න",
        "contact_us" to "FriendHub අමතන්න",
        "community_guidelines" to "ප්‍රජා මාර්ගෝපදේශ",
        "privacy_policy" to "පෞද්ගලිකත්ව ප්‍රතිපත්තිය",
        "terms_of_service" to "සේවා කොන්දේසි",
        "app_version" to "යෙදුම් අනුවාදය",
        "opt_everyone" to "සියල්ලන්ටම (Everyone)",
        "opt_friends" to "මිතුරන්ට පමණි (Friends)",
        "opt_only_me" to "මට පමණි (Only Me)",
        "opt_friends_of_friends" to "මිතුරන්ගේ මිතුරන්ට",
        "opt_no_one" to "කිසිවෙකුට නොවේ (No One)"
    )

    private val tamilStrings = mapOf(
        "settings_title" to "அமைப்புகள் (Settings)",
        "settings_subtitle" to "உங்கள் FriendHub கணக்கை நிர்வகிக்கவும்",
        "view_profile" to "சுயவிவரத்தைக் காண்க",
        "category_account" to "கணக்கு (Account)",
        "category_privacy" to "தனியுரிமை (Privacy)",
        "category_notifications" to "அறிவிப்புகள் (Notifications)",
        "category_appearance" to "தோற்றம் (Appearance)",
        "category_content" to "உள்ளடக்கம் & மீடியா",
        "category_language" to "மொழி (Language)",
        "category_security" to "பாதுகாப்பு (Security)",
        "category_data" to "தரவு & சேமிப்பு",
        "category_help" to "உதவி & ஆதரவு",
        "category_about" to "பற்றி (About)",
        "category_session" to "அமர்வு (Session)",
        "log_out" to "வெளியேறு (Log Out)",
        "log_out_confirm_title" to "FriendHub-ல் இருந்து வெளியேறவா?",
        "log_out_confirm_msg" to "இந்த சாதனத்திலிருந்து நீங்கள் வெளியேற விரும்புகிறீர்களா?",
        "cancel" to "ரத்துசெய்",
        "save" to "சேமிக்கவும்",
        "saved" to "அமைப்புகள் சேமிக்கப்பட்டன ✓",
        "delete_account" to "கணக்கை நீக்கு (Delete Account)",
        "delete_account_warn" to "உங்கள் கணக்கை நீக்குவது உங்கள் சுயவிவரம் மற்றும் இடுகைகளை நிரந்தரமாக நீக்கும்.",
        "account_info" to "கணக்கு தகவல்",
        "email_phone" to "மின்னஞ்சல் & தொலைபேசி",
        "password_security" to "கடவுச்சொல் & பாதுகாப்பு",
        "login_activity" to "உள்நுழைவு செயல்பாடு",
        "connected_devices" to "இணைக்கப்பட்ட சாதனங்கள்",
        "profile_visibility" to "சுயவிவர பார்வை",
        "friend_requests" to "நண்பர் கோரிக்கை",
        "who_can_message" to "செய்தி அனுப்பக்கூடியவர்கள்",
        "who_can_see_posts" to "இடுகைகளைப் பார்க்கக்கூடியவர்கள்",
        "who_can_see_stories" to "Stories பார்க்கக்கூடியவர்கள்",
        "online_status" to "ஆன்லைன் நிலை",
        "last_active" to "கடைசியாக செயலில் இருந்த நிலை",
        "read_receipts" to "படித்த ரசீதுகள் (Read Receipts)",
        "blocked_users" to "தடுக்கப்பட்ட பயனர்கள்",
        "push_notif" to "Push அறிவிப்புகள்",
        "msg_notif" to "செய்தி அறிவிப்புகள்",
        "likes_notif" to "விருப்பங்கள் & எதிர்வினைகள்",
        "comments_notif" to "கருத்துகள்",
        "mentions_notif" to "குறிப்பிடுதல்கள்",
        "stories_notif" to "Story அறிவிப்புகள்",
        "email_notif" to "மின்னஞ்சல் அறிவிப்புகள்",
        "theme" to "கருப்பொருள் (Theme)",
        "theme_dark" to "இருண்ட (Dark)",
        "theme_light" to "ஒளி (Light)",
        "theme_system" to "கணினி இயல்புநிலை",
        "autoplay_videos" to "வீடியோ தானாக இயங்குதல்",
        "data_saver" to "தரவு சேமிப்பான்",
        "upload_quality" to "பதிவேற்ற தரம்",
        "auto_download" to "தானாகப் பதிவிறக்குதல்",
        "sensitive_content" to "உணர்திறன் எச்சரிக்கை",
        "two_factor" to "இருபடி சரிபார்ப்பு (2FA)",
        "login_alerts" to "உள்நுழைவு எச்சரிக்கைகள்",
        "app_lock" to "பயன்பாட்டு பூட்டு",
        "clear_cache" to "தற்காலிக சேமிப்பை அழி",
        "storage_usage" to "சேமிப்பக பயன்பாடு",
        "help_center" to "உதவி மையம்",
        "report_problem" to "சிக்கலைப் புகாரளிக்கவும்",
        "contact_us" to "FriendHub-ஐத் தொடர்பு கொள்ளவும்",
        "community_guidelines" to "சமூக வழிகாட்டுதல்கள்",
        "privacy_policy" to "தனியுரிமைக் கொள்கை",
        "terms_of_service" to "சேவை விதிமுறைகள்",
        "app_version" to "பயன்பாட்டு பதிப்பு",
        "opt_everyone" to "அனைவரும்",
        "opt_friends" to "நண்பர்கள் மட்டும்",
        "opt_only_me" to "நான் மட்டும்",
        "opt_friends_of_friends" to "நண்பர்களின் நண்பர்கள்",
        "opt_no_one" to "யாரும் இல்லை"
    )
}
